seed: 42
nodes_config:
  type: 'raw'
  nodes:
    - name: "1"
      hashrate: 10
      peers: ["2"]
    - name: "2"
      hashrate: 10
      peers: ["3"]
    - name: "3"
      hashrate: 10
      peers: ["4"]
    - name: "4"
      hashrate: 10
      peers: ["1"]
